/**
 * @file
 * @brief BldTebData, the TEB input record that packs data from several BLD sources behind a bit mask of the sources present.
 */
#ifndef Pds_Trg_BldTebData_hh
#define Pds_Trg_BldTebData_hh

#include <string>
#include <cstdint>

namespace Pds {
  /** Namespace of the psdaq trigger code: TEB input data records, trigger primitives and trigger decisions. */
  namespace Trg {
    class GmdTebData;
    class XGmdTebData;
    class PhaseCavityTebData;
    class EBeamTebData;
    class GasDetTebData;

    /** TEB input record for BLD: a 64-bit mask of sources present, followed by the record of each present source in BldSource order. The accessor functions generated by DATADEF return a pointer to a source record, or null if that source is absent. */
    class BldTebData
    {
    public:
      /** BLD sources, in the order of their bits in sources and of their records after the header. */
      enum BldSource { gmd_, /**< Bit 0: gmd (GmdTebData). */ xgmd_, /**< Bit 1: xgmd (XGmdTebData). */ pcav_, /**< Bit 2: pcav (PhaseCavityTebData). */ pcavs_, /**< Bit 3: pcavs (PhaseCavityTebData). */  gasdet_, /**< Bit 4: gasdet (GasDetTebData). */ ebeam_, /**< Bit 5: ebeam (EBeamTebData). */ ebeams_, /**< Bit 6: ebeams (EBeamTebData). */ NSOURCES  /**< Number of sources (7); also returned by lookup() for an unknown name. */ };
      /** Return the source whose name (gmd, xgmd, pcav, pcavs, gasdet, ebeam, ebeams) equals detName, or NSOURCES if none does. */
      static BldSource lookup(const std::string& detName);
      /** Return the largest record size: the header plus the records of all sources. */
      static unsigned sizeof_();

      /** Store the mask of sources present. */
      BldTebData(uint64_t sources_) : sources(sources_) {}

/** Defines an accessor N() that returns the record of source N cast to T*, or null if the bit N_ is not set in sources. */
#define DATADEF(N,T)  T* N() \
        { return (sources>>N##_)&1 ? reinterpret_cast<T*>((char*)this+offset_(N##_)) : 0; }

      DATADEF(gmd   ,GmdTebData)
      DATADEF(xgmd  ,XGmdTebData)
      DATADEF(pcav  ,PhaseCavityTebData)
      DATADEF(pcavs ,PhaseCavityTebData)
      DATADEF(gasdet,GasDetTebData)
      DATADEF(ebeam ,EBeamTebData)
      DATADEF(ebeams,EBeamTebData)

      // GmdTebData&         gmd ();
      // XGmdTebData&        xgmd();
      // PhaseCavityTebData& pcav();

      /** Return the byte offset of the record of source src: the header size plus the sizes of the present sources before it. */
      unsigned offset_(unsigned);

      uint64_t sources;  ///< Bit mask of the sources whose records follow (bit numbers from BldSource).
    };
  };
};

#endif
